services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_ENV=production
      # - PORT=5000
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:${PORT:-5000}/health || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 12
    #   start_period: 30s
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      # backend:
      #   condition: service_healthy
      - backend
    restart: unless-stopped